### ISSUE TITLE
Improve the pagination of the blog

### ISSUE THREAD

**Issue by emma-sax4** [emma-sax4/emma-sax4.github.io#59]
## Is this feature request related to a problem?
There's no problem right now. The existing pagination bar works as expected.

## The Solution I'd Prefer
Use a different paginator that contains a `Previous` and `Next` button (or `Newer` and `Older`). Keep the existing set/tag collection pages and allow pagination on those as well. Another requirement for me is that the URL of the blog doesn't have a trailing `/` at the end:
```
emmasax4.info/blog/
emmasax4.info/blog/page/2/
```
versus
```
emmasax4.info/blog
emmasax4.info/blog/page/2
```

## Alternative Solutions I've Considered
I've looked at using [`jekyll-paginate-v2`](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md) already, and even had a test branch. Although this worked fairly well right away, my URL condition wasn't met. I'd also have to do more work to get the collection organizing pages working.

The current pagination uses [`list.js` pagination](https://listjs.com/docs/pagination/). However, the documentation for `list.js` isn't great which may end up being the reason why I want to switch pagination types. It looks like it doesn't give me the flexibility of easily adding `Previous`/`Next` buttons.

One other thing that I didn't really try in detail was the original [Jekyll pagination](https://jekyllrb.com/docs/pagination/). I suppose I could take a closer look at that. The documentation in that isn't as full as the documentation and examples in  `jekyll-paginate-v2`, so that's the biggest thing there.

Either way, I may have to end up recruiting someone to help me find the best option for my blog.

## Additional Context
No additional context necessary. I also looked at what @BrianMitchL implements [here](https://brianm.me/blog/). It looks like that project is using the traditional Jekyll pagination.

**Comment by BrianMitchL** [comment]
To use Jekyll for pagination, you will need to look past wanting to remove trailing slashes with the URLs. Removing the trailing slash still resolves and loads the right content, but this is done by the GitHub Pages, separate from your app code. I found that Jekyll pagination was pretty easy, and nice that it's already built in to the existing structure.

**Comment by emma-sax4** [comment]
Oh Hi Brian! I didn't expect you to actually look at this! I was more just taking notes of what I was peeking at.

Yeah when I peeked at it, I actually got a decent amount of it working on my blog. The only issue is that I hand-crafted post collection sorting and filtering based on the collection showing. So to use Jekyll's built-in pagination, I'd have to scrap that and use their stuff instead.

**Comment by BrianMitchL** [comment]
You tagged me to I got an alert 🙂 Ah, yeah that'd be more work then.

**Comment by emma-sax4** [comment]
Working pull request here: https://github.com/emma-sax4/emma-sax4.github.io/pull/85.

**Comment by emma-sax4** [comment]
I ended up just deciding to deal with the URL condition, to allow the trailing slashes. It's not a big deal. I may just make the whole website have trailing slashes.
